
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 8;
  public static final int DIVIDE = 45;
  public static final int STRING_LITERAL = 30;
  public static final int CHAR = 3;
  public static final int CONCAT = 51;
  public static final int CHAR_LITERAL = 26;
  public static final int POOL = 21;
  public static final int BADCHAR = 58;
  public static final int EXPO = 47;
  public static final int INT = 5;
  public static final int RAT_LITERAL = 28;
  public static final int MINUS = 44;
  public static final int AND = 49;
  public static final int NOT = 48;
  public static final int SEMICOLON = 39;
  public static final int RPAR = 32;
  public static final int OR = 50;
  public static final int LESSTHAN = 33;
  public static final int IN = 9;
  public static final int TDEF = 10;
  public static final int COMMA = 40;
  public static final int BOOL = 4;
  public static final int FI = 17;
  public static final int RAT = 6;
  public static final int MULTIPLY = 46;
  public static final int PLUS = 43;
  public static final int LOOP = 20;
  public static final int ASSIGN = 41;
  public static final int MAIN = 13;
  public static final int IF = 16;
  public static final int DOT = 55;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int NOEQ = 54;
  public static final int RETURN = 23;
  public static final int EQUAL = 53;
  public static final int TRUE = 24;
  public static final int UNARY_PLUS = 57;
  public static final int error = 1;
  public static final int BREAK = 22;
  public static final int FDEF = 12;
  public static final int LBRACK = 37;
  public static final int COLON = 42;
  public static final int LBRACE = 35;
  public static final int ELSE = 19;
  public static final int RBRACK = 38;
  public static final int READ = 14;
  public static final int MORETHAN = 34;
  public static final int LESS_EQ = 52;
  public static final int FLOAT = 7;
  public static final int RBRACE = 36;
  public static final int THEN = 18;
  public static final int LPAR = 31;
  public static final int ALIAS = 11;
  public static final int FLOAT_LITERAL = 29;
  public static final int FALSE = 25;
  public static final int UNARY_MINUS = 56;
  public static final int PRINT = 15;
  public static final int INT_LITERAL = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CHAR",
  "BOOL",
  "INT",
  "RAT",
  "FLOAT",
  "SEQ",
  "IN",
  "TDEF",
  "ALIAS",
  "FDEF",
  "MAIN",
  "READ",
  "PRINT",
  "IF",
  "FI",
  "THEN",
  "ELSE",
  "LOOP",
  "POOL",
  "BREAK",
  "RETURN",
  "TRUE",
  "FALSE",
  "CHAR_LITERAL",
  "INT_LITERAL",
  "RAT_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "LPAR",
  "RPAR",
  "LESSTHAN",
  "MORETHAN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "ASSIGN",
  "COLON",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "MULTIPLY",
  "EXPO",
  "NOT",
  "AND",
  "OR",
  "CONCAT",
  "LESS_EQ",
  "EQUAL",
  "NOEQ",
  "DOT",
  "UNARY_MINUS",
  "UNARY_PLUS",
  "BADCHAR"
  };
}

